### ISSUE TITLE
[refactor_classes] TODO

### ISSUE THREAD

**Issue by glemaitre** [glemaitre/scikit-cycling#5]
- [x] Write test for anaerobic modelling
- [x] Check the `max_duration_profile_` in `fit` function from `RecordPowerProfile`
- [x] Check that the list of `RidePowerProfile` called the `fit` function in `fit` function from `RecordPowerProfile`
- [x] Figure out how to load properly the power-profile; saving seems ok
